# Global build settings
[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# Environment variables
[build.environment]
  NODE_VERSION = "18.18.0"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NEXT_USE_NETLIFY_EDGE = "true"

# Plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Function settings
[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "node-cache",
    "node-fetch",
    "node-ical"  
  ]

# Redirects
[[redirects]]
  from = "/api/translations"
  to = "/.netlify/functions/translations"
  status = 200

[[redirects]]
  from = "/api/calendar"
  to = "/.netlify/functions/calendar"
  status = 200

[[redirects]]
  from = "/api/inaturalist"
  to = "/.netlify/functions/inaturalist"
  status = 200

[[redirects]]
  from = "/api/sideband/*"
  to = "/.netlify/functions/sideband-bridge/:splat"
  status = 200

# Catch-all for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add CORS headers for Next.js resources
[[headers]]
  for = "/_next/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://livada.bio"
    Access-Control-Allow-Methods = "GET, OPTIONS"

# Add CORS headers for static assets
[[headers]]
  for = "/static/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://livada.bio"
    Access-Control-Allow-Methods = "GET, OPTIONS"

# Add CORS headers for all other resources
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://livada.bio"
    Access-Control-Allow-Methods = "GET, OPTIONS"