[build]
  command = "npm install --legacy-peer-deps && next build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
