backend:
  name: github
  repo: belinau/livada-biotope
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: public/images/uploads
public_folder: /images/uploads

local_backend: true

# Editorial workflow: adds an interface for drafting, reviewing, and approving posts
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "English Title", name: "title_en", widget: "string" }
      - { label: "Slovenian Title", name: "title_sl", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "English Summary", name: "summary_en", widget: "text" }
      - { label: "Slovenian Summary", name: "summary_sl", widget: "text" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "English Content", name: "body_en", widget: "markdown" }
      - { label: "Slovenian Content", name: "body_sl", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "English Title", name: "title_en", widget: "string" }
      - { label: "Slovenian Title", name: "title_sl", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "English Summary", name: "summary_en", widget: "text" }
      - { label: "Slovenian Summary", name: "summary_sl", widget: "text" }
      - label: "Project Details"
        name: "details"
        widget: "object"
        fields:
          - { label: "Start Date", name: "startDate", widget: "date" }
          - { label: "End Date", name: "endDate", widget: "date", required: false }
          - { label: "Status", name: "status", widget: "select", options: ["In Progress", "Completed", "Planned"], required: false }
          - { label: "Partners", name: "partners", widget: "list", required: false }
      - { label: "English Content", name: "body_en", widget: "markdown" }
      - { label: "Slovenian Content", name: "body_sl", widget: "markdown" }

  - name: "gallery"
    label: "Gallery"
    folder: "src/content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "English Title", name: "title_en", widget: "string" }
      - { label: "Slovenian Title", name: "title_sl", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "English Description", name: "description_en", widget: "text", required: false }
      - { label: "Slovenian Description", name: "description_sl", widget: "text", required: false }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "English Caption", name: "caption_en", widget: "string", required: false }
          - { label: "Slovenian Caption", name: "caption_sl", widget: "string", required: false }
          - { label: "English Alt Text", name: "alt_en", widget: "string", required: false }
          - { label: "Slovenian Alt Text", name: "alt_sl", widget: "string", required: false }

  - name: "resource_library"
    label: "Resource Library"
    folder: "src/content/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "English Title", name: "title_en", widget: "string" }
      - { label: "Slovenian Title", name: "title_sl", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "English Body", name: "body_en", widget: "markdown" }
      - { label: "Slovenian Body", name: "body_sl", widget: "markdown" }

  - name: "resource_pages"
    label: "Resource Guides"
    files:
      - label: "Ecofeminism Resources"
        name: "ecofeminism_resources"
        file: "src/content/resources/ecofeminism.md"
        fields:
          - { label: "English Title", name: "title_en", widget: "string" }
          - { label: "Slovenian Title", name: "title_sl", widget: "string" }
          - label: "Introduction"
            name: "introduction"
            widget: "object"
            fields:
              - label: "English"
                name: "en"
                widget: "text"
              - label: "Slovenian"
                name: "sl"
                widget: "text"
          - label: "What is Ecofeminism"
            name: "whatIsEcofeminism"
            widget: "object"
            fields:
              - label: "English"
                name: "en"
                widget: "markdown"
              - label: "Slovenian"
                name: "sl"
                widget: "markdown"
          - label: "Key Concepts"
            name: "keyConcepts"
            widget: "object"
            fields:
              - label: "English"
                name: "en"
                widget: "markdown"
              - label: "Slovenian"
                name: "sl"
                widget: "markdown"
          - label: "Recommended Readings"
            name: "readings"
            widget: "list"
            fields:
              - { label: "English Title", name: "title_en", widget: "string" }
              - { label: "Slovenian Title", name: "title_sl", widget: "string" }
              - { label: "Author", name: "author", widget: "string" }
              - label: "Description"
                name: "description"
                widget: "object"
                fields:
                  - { label: "English", name: "en", widget: "text" }
                  - { label: "Slovenian", name: "sl", widget: "text" }
              - { label: "Link", name: "link", widget: "string", required: false }
          - label: "Media Resources"
            name: "media"
            widget: "list"
            fields:
              - { label: "English Title", name: "title_en", widget: "string" }
              - { label: "Slovenian Title", name: "title_sl", widget: "string" }
              - { label: "Creator", name: "creator", widget: "string", required: false }
              - label: "Description"
                name: "description"
                widget: "object"
                fields:
                  - { label: "English", name: "en", widget: "text" }
                  - { label: "Slovenian", name: "sl", widget: "text" }
              - { label: "Link", name: "link", widget: "string", required: false }
              - { label: "Type", name: "type", widget: "select", options: ["Video", "Podcast", "Article", "Other"], required: false }
      - label: "Instructables"
        name: "instructables"
        file: "src/content/resources/instructables.md"
        fields:
          - { label: "English Title", name: "title_en", widget: "string" }
          - { label: "Slovenian Title", name: "title_sl", widget: "string" }
          - label: "Introduction"
            name: "introduction"
            widget: "object"
            fields:
              - label: "English"
                name: "en"
                widget: "text"
              - label: "Slovenian"
                name: "sl"
                widget: "text"
          - label: "Instructables"
            name: "instructables"
            widget: "list"
            fields:
              - { label: "English Title", name: "title_en", widget: "string" }
              - { label: "Slovenian Title", name: "title_sl", widget: "string" }
              - label: "Description"
                name: "description"
                widget: "object"
                fields:
                  - { label: "English", name: "en", widget: "markdown" }
                  - { label: "Slovenian", name: "sl", widget: "markdown" }
              - label: "Materials"
                name: "materials"
                widget: "list"
                required: false
                fields:
                  - { label: "English Name", name: "name_en", widget: "string" }
                  - { label: "Slovenian Name", name: "name_sl", widget: "string" }
                  - { label: "Quantity", name: "quantity", widget: "string", required: false }
              - label: "Steps"
                name: "steps"
                widget: "list"
                fields:
                  - { label: "English Instruction", name: "instruction_en", widget: "markdown" }
                  - { label: "Slovenian Instruction", name: "instruction_sl", widget: "markdown" }
                  - { label: "Image", name: "image", widget: "image", required: false }
              - { label: "Difficulty", name: "difficulty", widget: "select", options: ["Easy", "Medium", "Hard"], required: false }
              - { label: "Time Required (minutes)", name: "timeRequired", widget: "number", required: false }
              - { label: "Tags", name: "tags", widget: "list", required: false }

  - name: "translations"
    label: "Translations"
    files:
      - label: "Common Translations"
        name: "common_translations"
        file: "src/content/translations/common.md"
        fields:
          - { label: "Translation Key", name: "key", widget: "string" }
          - { label: "English Text", name: "en", widget: "string" }
          - { label: "Slovenian Text", name: "sl", widget: "string" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/content/pages/home.md"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "English Title", name: "title_en", widget: "string" }
              - { label: "Slovenian Title", name: "title_sl", widget: "string" }
              - { label: "English Subtitle", name: "subtitle_en", widget: "string" }
              - { label: "Slovenian Subtitle", name: "subtitle_sl", widget: "string" }
              - { label: "Background Image", name: "image", widget: "image" }
          - label: "About Section"
            name: "about"
            widget: "object"
            fields:
              - { label: "English Title", name: "title_en", widget: "string" }
              - { label: "Slovenian Title", name: "title_sl", widget: "string" }
              - { label: "English Content", name: "content_en", widget: "markdown" }
              - { label: "Slovenian Content", name: "content_sl", widget: "markdown" }
              - { label: "Image", name: "image", widget: "image", required: false }
          - label: "Featured Projects"
            name: "featuredProjects"
            widget: "list"
            fields:
              - { label: "Project Slug", name: "slug", widget: "string" }
          - label: "Call to Action"
            name: "cta"
            widget: "object"
            fields:
              - { label: "English Title", name: "title_en", widget: "string" }
              - { label: "Slovenian Title", name: "title_sl", widget: "string" }
              - { label: "English Content", name: "content_en", widget: "markdown" }
              - { label: "Slovenian Content", name: "content_sl", widget: "markdown" }
              - { label: "English Button Text", name: "buttonText_en", widget: "string" }
              - { label: "Slovenian Button Text", name: "buttonText_sl", widget: "string" }
              - { label: "Button Link", name: "buttonLink", widget: "string" }
              - { label: "Background Image", name: "image", widget: "image", required: false }