# This configuration enables a professional, bilingual gallery workflow.

backend:
  name: git-gateway
  branch: main

# Global i18n configuration remains the same.
i18n:
  structure: multiple_files
  locales: [sl, en]
  default_locale: sl

# Media will be uploaded to this folder
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "strani"
    label: "Urejanje Strani"
    folder: "public/content/pages" # Changed from "files" to "folder"
    i18n: true # This tells the collection to use the global i18n settings
    fields:
      # These fields will now be translated in separate files.
      - { label: "Naslov Strani", name: "title", widget: "string", i18n: true }
      # The main content of the page is now the "body".
      - { label: "Vsebina Strani", name: "body", widget: "markdown", i18n: true }

  - name: "posts"
    label: "Zapisi"
    folder: "public/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    i18n: true
    fields:
      - { label: "Naslov", name: "title", widget: "string", i18n: true }
      - { label: "Datum objave", name: "date", widget: "datetime" }
      - { label: "Oznake (Tags)", name: "tags", widget: "list", required: false, i18n: true }
      - { label: "Vsebina", name: "body", widget: "markdown", i18n: true }

  - name: "practices"
    label: "Utelešenja"
    folder: "public/content/practices"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Naslov", name: "title", widget: "string", i18n: true }
      - { label: "Datum objave", name: "date", widget: "datetime" }
      - { label: "Oznake (Tags)", name: "tags", widget: "list", required: false, i18n: true }
      - label: "Vsebina"
        name: "body"
        widget: "markdown"
        i18n: true
        editor_components:
          - mermaid
          - youtube
          - vimeo
          - accordion

  # The gallery collection remains special, as requested.
  - name: "galleries"
    label: "Galerije"
    folder: "public/content/galleries"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Naslov Galerije", name: "title", widget: "string", i18n: true }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Avtor fotografij", name: "author", widget: "string", required: false }
      - { label: "Opis Galerije", name: "description", widget: "text", i18n: true, required: false }
      - name: "images"
        label: "Slike"
        widget: "list"
        fields:
          - { label: "Slika", name: "image", widget: "image" }
          - { label: "Podnapis (SL)", name: "caption_sl", widget: "string", required: false }
          - { label: "Caption (EN)", name: "caption_en", widget: "string", required: false }