# This configuration enables a professional, bilingual gallery workflow.

backend:
  name: git-gateway
  branch: main

# Global i18n configuration remains the same.
i18n:
  structure: multiple_files
  locales: [sl, en]
  default_locale: sl

# Media will be uploaded to this folder
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  # --- CORRECTED "File Collection" ---
  # This collection now correctly overrides the global i18n setting.
  - name: "strani"
    label: "Urejanje Strani"
    # This i18n block tells this collection to use single_file mode, resolving the error.
    i18n:
      structure: single_file
    files:
      - name: "intertwinings_page"
        label: "Stran Prepletanja (senzorji)"
        file: "public/content/pages/intertwinings.md"
        # This i18n flag enables the translation UI for the file.
        i18n: true
        fields:
          # These fields will now be translated within the single intertwinings.md file.
          - { label: "Glavni naslov strani", name: "title", widget: "string", i18n: true }
          - { label: "Besedilo pod naslovom", name: "description", widget: "markdown", i18n: true }

  - name: "posts"
    label: "Zapisi"
    folder: "public/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    i18n: true
    fields:
      - { label: "Naslov", name: "title", widget: "string", i18n: true }
      - { label: "Datum objave", name: "date", widget: "datetime" }
      - { label: "Oznake (Tags)", name: "tags", widget: "list", required: false, i18n: true }
      - { label: "Vsebina", name: "body", widget: "markdown", i18n: true }

  - name: "practices"
    label: "Utelešenja"
    folder: "public/content/practices"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Naslov", name: "title", widget: "string", i18n: true }
      - { label: "Datum objave", name: "date", widget: "datetime" }
      - { label: "Oznake (Tags)", name: "tags", widget: "list", required: false, i18n: true }
      - { label: "Vsebina", name: "body", widget: "markdown", i18n: true }
  
  - name: "galleries"
    label: "Galerije"
    folder: "public/content/galleries" 
    create: true
    slug: "{{slug}}"
    i18n: true 
    fields:
      - { label: "Naslov Galerije", name: "title", widget: "string", i18n: true }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Avtor fotografij", name: "author", widget: "string", required: false }
      - { label: "Opis Galerije", name: "description", widget: "text", i18n: true, required: false }
      - name: "images"
        label: "Slike"
        widget: "list"
        fields:
          - { label: "Slika", name: "image", widget: "image" }
          - { label: "Podnapis (SL)", name: "caption_sl", widget: "string", required: false }
          - { label: "Caption (EN)", name: "caption_en", widget: "string", required: false }
